# templates/service-influxdb.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.names.deployment }}
  name: {{ .Values.names.serviceInfluxDB }}
spec:
  selector:
    app: {{ .Values.names.deployment }}
  ports:
    - name: influxdb
      protocol: TCP
      port: 8086
      targetPort: 8086
