apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.names.deployment }}
  name: {{ .Values.names.serviceExternal }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: {{ .Values.names.deployment }}
