# values.yaml
replicaCount: 1

names:
  deployment: influx-nodejs-app
  serviceExternal: influx-nodejs-app-external
  serviceInfluxDB: influxdb-service

nodejs:
  image:
    repository: your/nodejs-app
    tag: "latest"
    pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9999
  nodePort: 31234

influxdb:
  token: ""
  org: ""
  bucket: ""
